--QUERYS DDL--
--CRIANDO TABELAS--
CREATE TABLE dados_operadoras (
	id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	registro_ans VARCHAR(6) NOT NULL,
	razao_social VARCHAR(200) NOT NULL,
	cnpj VARCHAR(14) NOT NULL,
	modalidade VARCHAR(100) NOT NULL,
	uf VARCHAR(2) NOT NULL,
	trimestre VARCHAR(2) NOT NULL,
	ano VARCHAR(4) NOT NULL,
	valor_despesas DECIMAL NOT NULL
);
CREATE TABLE despesas_agregadas (
	id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	razao_social VARCHAR(200) NOT NULL,
	uf VARCHAR(2) NOT NULL,
	valor_total DECIMAL NOT NULL,
	media DECIMAL NOT NULL,
	desvio_padrao DECIMAL
);
SELECT * FROM dados_operadoras;

--QUERYS ANALITICAS--

--QUERY 1--
WITH periodos AS (
    SELECT 
        registro_ans,
        razao_social,
        MIN(ano || trimestre) AS primeiro_periodo,
        MAX(ano || trimestre) AS ultimo_periodo
    FROM dados_operadoras
    GROUP BY registro_ans, razao_social
),
valores AS (
    SELECT 
        p.registro_ans,
        p.razao_social,
        d1.valor_despesas AS valor_inicial,
        d2.valor_despesas AS valor_final
    FROM periodos p
    JOIN dados_operadoras d1
        ON d1.registro_ans = p.registro_ans
        AND (d1.ano || d1.trimestre) = p.primeiro_periodo
    JOIN dados_operadoras d2
        ON d2.registro_ans = p.registro_ans
        AND (d2.ano || d2.trimestre) = p.ultimo_periodo
)
SELECT 
    registro_ans,
    razao_social,
    valor_inicial,
    valor_final,
    ROUND(
        ((valor_final - valor_inicial) / valor_inicial) * 100,
        2
    ) AS crescimento_percentual
FROM valores
ORDER BY crescimento_percentual DESC
LIMIT 5;

--QUERY 2--
SELECT 
    uf,
    SUM(valor_total) AS despesas_totais
FROM despesas_agregadas
GROUP BY uf
ORDER BY despesas_totais DESC
LIMIT 5;

--QUERY 3--
WITH operadoras_acima_media AS (
    SELECT 
        d.registro_ans,
        d.razao_social,
        COUNT(*) AS trimestres_acima_media
    FROM dados_operadoras d
    WHERE d.valor_despesas > (
        SELECT AVG(media)
        FROM despesas_agregadas
    )
    GROUP BY d.registro_ans, d.razao_social
)
SELECT COUNT(*) AS total_operadoras
FROM operadoras_acima_media
WHERE trimestres_acima_media >= 2;